version: '3.8'

services:
  code-challenge:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: code-challenge
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    external: true
